project_id = "oroxkzqbbhgreismkmbc"

[functions.edit-page-ai]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.analyze-product]
verify_jwt = false

[functions.makeup-recommendations]
verify_jwt = false

[functions.timeline-ai]
verify_jwt = false

[functions.analyze-skin]
verify_jwt = false

[functions.skincare-chat]
verify_jwt = false